version: "3"
networks:
  site15-network:
    ipam:
      config:
        - subnet: "172.12.0.0/16"

volumes:
  site15-postgresql:
    external: true
  site15-redis:
    external: true

services:
  site15-nginx:
    image: nginx:alpine
    ports:
      - "9090:9090"
    container_name: "site15-nginx"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    networks:
      - site15-network
    depends_on:
      - site15-frontend
      - site15-backend

  site15-frontend:
    image: node:12
    user: $UID:$GID
    container_name: "site15-frontend-service"
    env_file:
    - ../../env/local.env
    working_dir: "/app"
    volumes:
      - ./../../:/app
    networks:
      - site15-network
    ports:
      - "4200:4200"
    command: "npm run start:dev:frontend"
    tty: true
    depends_on:
      - site15-postgres
      - site15-redis
      - site15-backend

  site15-backend:
    image: node:12
    user: $UID:$GID
    container_name: "site15-backend-service"
    env_file:
    - ../../env/local.env
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@site15-postgres:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DATABASE}?schema=public
    working_dir: "/app"
    volumes:
      - ./../../:/app
    networks:
      - site15-network
    ports:
      - "5000:5000"
    command: "npm run start:dev:backend"
    tty: true
    depends_on:
      - site15-postgres
      - site15-redis

  site15-postgres:
    image: "postgres:13"
    container_name: "site15-postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
    - ../../env/local.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - site15-postgresql:/var/lib/postgresql/site15_data
    networks:
      - site15-network

  site15-redis:
    image: redis:6-alpine
    container_name: "site15-redis"
    env_file:
    - ../../env/local.env
    command: ["redis-server"]
    ports:
      - "32379:6379"
    volumes:
      - site15-redis:/data
    networks:
      - site15-network
