version: "3"
networks:
  site15-network:
    ipam:
      config:
        - subnet: "172.12.0.0/16"

volumes:
  site15-postgresql:
    external: true
  site15-redis:
    external: true

services:
  site15-nginx:
    image: nginx:alpine
    ports:
      - "9090:9090"
    container_name: "site15-nginx"
    env_file:
    - ../../env/local.env
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    networks:
      - site15-network
    depends_on:
      - site15-client
      - site15-server

  site15-client:
    image: node:12
    user: $UID:$GID
    container_name: "site15-client-service"
    env_file:
    - ../../env/local.env
    working_dir: "/app"
    volumes:
      - ./../../:/app
    networks:
      - site15-network
    ports:
      - "4200:4200"
    command: "npm run start:dev:client"
    tty: true

  site15-server:
    image: node:12
    user: $UID:$GID
    container_name: "site15-server-service"
    env_file:
    - ../../env/local.env
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@site15-postgres:5432/site15?schema=public
    working_dir: "/app"
    volumes:
      - ./../../:/app
    networks:
      - site15-network
    ports:
      - "5000:5000"
    command: "npm run start:dev:server"
    tty: true
    depends_on:
      - site15-postgres
      - site15-redis

  site15-postgres:
    image: "postgres:12"
    container_name: "site15-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=site15
    env_file:
    - ../../env/local.env
    ports:
      - "32432:5432"
    volumes:
      - site15-postgresql:/var/lib/postgresql/site15_data
    networks:
      - site15-network

  site15-redis:
    image: redis:6-alpine
    container_name: "site15-redis"
    env_file:
    - ../../env/local.env
    command: ["redis-server"]
    ports:
      - "32379:6379"
    volumes:
      - site15-redis:/data
    networks:
      - site15-network
