version: '3'

services:
  site15-backend-with-frontend.conf:
    image: 'site15/backend-with-frontend'
    build:
      context: ../../
      dockerfile: ./docker/__Dockerfile/Dockerfile.site15-backend-with-frontend

  site15-backend:
    image: 'site15/backend'
    build:
      context: ../../
      dockerfile: ./docker/__Dockerfile/Dockerfile.site15-backend
    user: $UID:$GID

  site15-frontend:
    image: 'site15/frontend'
    build:
      context: ../../
      dockerfile: ./docker/__Dockerfile/Dockerfile.site15-frontend