version: '3'
networks:
  site15-network:
    ipam:
      config:
        - subnet: '172.12.0.0/16'

services:
  site15-server-with-static:
    image: 'site15/server-with-static'
    container_name: 'site15-server-with-static-service'
    volumes:
      - ./prod/logs:/var/log/nginx/
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile.site15-server-with-static
    networks:
      - site15-network
    ports:
      - '9090:9090'
    tty: true
    depends_on:
      - site15-server

  site15-server:
    image: 'site15/server'
    user: $UID:$GID
    container_name: 'site15-server-service'
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile.site15-server
    networks:
      - site15-network
    tty: true