kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: global-postgres-prod
  name: global-postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/global-postgres-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: global-postgres-prod
  name: global-postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
