FROM nginx:alpine
LABEL maintainer="admin@site15.ru"
COPY ./docker/prod/nginx/nginx-backend-with-frontend.conf /etc/nginx/conf.d/nginx-backend-with-frontend.conf
COPY ./dist/apps/site15-frontend /usr/share/nginx/html