FROM node:12
LABEL maintainer="admin@site15.ru"
WORKDIR /usr/src/app
COPY ./apps/site15-server/package.json ./
COPY ./prisma/schema.prisma ./
RUN npm config set package-lock false
RUN npm i --only=production
RUN npm run prisma:generate
COPY ./dist/apps/site15-server .
EXPOSE 5000
STOPSIGNAL SIGINT
CMD ["npm", "start"]