apiVersion: v1
kind: Service
metadata:
  namespace: global-postgres-prod
  name: site15-global-postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 32432
  selector:
    app: postgres
