apiVersion: v1
kind: Service
metadata:
  namespace: postgres-prod
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 32432
  selector:
    app: postgres
